# Maintainer: tbaublys@splunk.com

[ui]
is_visible = 1
show_in_nav = true
label = Whiteboard App

[launcher]
author = Tomas Baublys
description = Collaborative whiteboard for Splunk platform and use case design. Documentation: https://github.com/bautt/splunk-whiteboard-app/blob/main/README.md
version = 0.3.51

[package]
check_for_updates = false
id = whiteboard_app

[id]
name = whiteboard_app
version = 0.3.51

[install]
allows_disable = true
python.version = python3
